name = "hussamfaroug-com"
main = "hussamfaroug-com-worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

routes = [
  { pattern = "hussamfaroug.com/*", zone_name = "hussamfaroug.com" }
]

[[kv_namespaces]]
binding = "SITE_CONFIG"
id = "b36f257a4cb045028cbc637027acb086"
